from semantic_router import Route
from semantic_router.routers import SemanticRouter
from semantic_router.encoders import HuggingFaceEncoder
from semantic_router.index.local import LocalIndex

encoder = HuggingFaceEncoder(
    name="sentence-transformers/all-MiniLM-L6-v2"
)

faq = Route(
    name="FAQ",
    utterances=[
        "What is your return policy?",
        "Can I return a product if I'm not satisfied?",
        "How do I track my order?",
        "How many days does delivery take?",
        "Do you offer cash on delivery?",
        "What if I receive the wrong item?",
        "Can I exchange my product?",
        "What is your refund timeline?",
        "Are shipping charges refundable?",
        "Do you deliver to remote areas?",
        "Is same-day delivery available?",
        "What are the payment options?",
        "Can I cancel my order after placing it?",
        "How do I modify my order?",
        "Will I be notified once my order is shipped?",
        "Is GST included in the product price?",
        "How do I apply a coupon code?",
        "Do you offer student discounts?",
        "Can I use two discount codes at once?",
        "Where can I find my invoice?",
        "Can I get a printed invoice?",
        "How secure is the payment process?",
        "Do you store my card details?",
        "Is EMI available?",
        "Do you have wallet payment options?",
        "How do I contact customer support?",
        "Do you offer 24/7 support?",
        "What are your working hours?",
        "Can I chat with a customer care agent?",
        "Do you ship internationally?",
        "Is international shipping free?",
        "Are there any custom charges?",
        "Can I pay in foreign currency?",
        "Is my personal information safe?",
        "Do you share my data with third parties?",
        "What if the product is out of stock?",
        "Will I be notified when the product is back in stock?",
        "Do you offer gift wrapping?",
        "Can I write a gift message?",
        "Is there a loyalty program?",
        "How can I earn reward points?",
        "What do I do if I forget my password?",
        "How do I update my address?",
        "Can I change my email ID?",
        "How do I deactivate my account?",
        "Is there a mobile app available?",
        "Can I shop via the app?",
        "Does the app offer exclusive deals?",
        "Can I view my order history?",
        "What if I received a defective product?",
        "Will I get a full refund for defective items?",
        "What is your exchange policy?",
        "Do you offer partial refunds?",
        "Can I return only one item from a combo?",
        "Are sale items eligible for returns?",
        "Do you offer in-store returns?",
        "What happens if I miss the delivery?",
        "Can someone else receive my order?",
        "What if my payment fails?",
        "Can I reorder a past item?",
        "How do I subscribe to your newsletter?",
        "Can I unsubscribe from SMS alerts?",
        "Is there a return fee?",
        "Can I track my refund status?",
        "Do you issue credit notes?",
        "Can I use gift cards online?",
        "Where can I check my gift card balance?",
        "Can I combine multiple gift cards?",
        "How long is a gift card valid?",
        "Do you offer corporate gifting?",
        "Can I book an appointment for personal shopping?",
        "Do you offer virtual try-on?",
        "Can I pre-order upcoming products?",
        "What does 'Out for Delivery' mean?",
        "Can I request early delivery?",
        "Do you accept UPI payments?",
        "What is your cancellation policy?",
        "Can I cancel after it’s shipped?",
        "How do I raise a dispute?",
        "What is the difference between return and exchange?",
        "Do you offer warranty on products?",
        "Can I return electronics?",
        "Is there a pickup service for returns?",
        "Will I be charged for return pickup?",
        "What happens if my product gets damaged in transit?",
        "Can I schedule a return pickup?",
        "Are food items refundable?",
        "Do you provide installation service?",
        "Do you support bulk orders?",
        "Are all products authentic?",
        "Where do your products ship from?",
        "Can I pay later using PayLater services?",
        "Are there flash sales?",
        "Can I see upcoming deals?",
        "Is there a birthday discount?",
        "Can I earn cashback?",
        "Do you have any partner bank offers?",
        "Is packaging eco-friendly?",
        "What are your environmental policies?",
        "Do you have a recycle program?",
        "Can I refer friends for rewards?",
        "Where can I submit product feedback?",
        "How do I file a complaint?"
    ]
)


sql = Route(
    name="SQL",
    utterances=[
        "Show me Nike shoes under ₹3000.",
        "List Adidas shoes with 50% discount.",
        "Filter by size 9 Puma sneakers.",
        "I want men's sports shoes below ₹2000.",
        "Find Reebok running shoes in red.",
        "Show only formal shoes for women.",
        "List kids shoes under ₹1500.",
        "Filter shoes by white color and brand Adidas.",
        "Any slippers for ₹500 or less?",
        "Display sneakers sorted by price low to high.",
        "List boots under ₹4000 in black.",
        "Find waterproof shoes under ₹2500.",
        "Are there any unisex walking shoes?",
        "I want sandals with 30% or more discount.",
        "Do you have Bata size 10 under ₹2000?",
        "Show me top-rated hiking shoes.",
        "Any canvas shoes available under ₹1000?",
        "I want leather shoes for men.",
        "Find women’s high heel shoes on sale.",
        "Do you have flip flops under ₹600?",
        "Show me bestsellers in sneakers.",
        "What are the new arrivals in shoes?",
        "Find formal lace-up shoes for ₹2000.",
        "Show casual shoes in size 8 and blue color.",
        "I need budget-friendly kids shoes.",
        "Do you sell glow-in-the-dark shoes?",
        "Show orthopedic shoes for elderly.",
        "List shoes available in EMI under ₹5000.",
        "Filter men's shoes with customer rating above 4.",
        "Any vegan leather options?",
        "Show only shoes with return policy.",
        "Can I filter based on delivery time?",
        "Show Puma shoes in pink under ₹4000.",
        "Are there any combo shoe offers?",
        "I want shoes for trekking under ₹3000.",
        "Show formal shoes in stock now.",
        "List best value for money shoes.",
        "Show shoes that support wide feet.",
        "List branded sports shoes under 5k.",
        "Find eco-friendly footwear.",
        "Show school shoes under ₹1000.",
        "Do you have LED shoes?",
        "I want rainproof shoes under ₹2000.",
        "Display latest discounted sneakers.",
        "Show sandals with arch support.",
        "Filter athletic shoes for gym use.",
        "List women's flats under ₹1200.",
        "Show trending shoes this month.",
        "Any exclusive app-only offers?",
        "Sort by customer reviews.",
        "List size 7 to 9 shoes in stock.",
        "Show red and white colored shoes.",
        "Find shoes with free shipping.",
        "Display shoes from top brands only.",
        "Show Adidas shoes with rating above 4.5.",
        "List shoes with price drop today.",
        "Display products with cashback offer.",
        "Show shoes by season – summer collection.",
        "Do you have slip-resistant shoes?",
        "Show wedding wear footwear.",
        "Display sports shoes under ₹1500 with EMI.",
        "List orthopedic sandals under ₹2000.",
        "Do you have ankle boots?",
        "Find pastel-colored shoes.",
        "I want shoes made in India.",
        "Show gender-neutral shoe styles.",
        "Filter partywear heels for women.",
        "Are there any inventory clearance offers?",
        "Find black Adidas shoes below ₹3000.",
        "Show men's daily wear footwear.",
        "Display trending flip-flops.",
        "I want casual loafers in brown.",
        "Find office wear shoes for women.",
        "Show all Puma size 9 shoes under ₹3500.",
        "Find the cheapest shoes available.",
        "List items with no delivery fee.",
        "Show recently viewed shoes.",
        "Display top-rated deals today.",
        "I want wedges under ₹2500.",
        "Find hiking shoes with ankle support.",
        "Show black formal shoes under ₹1800.",
        "Filter sports shoes by running and gym.",
        "List high ankle shoes for trekking.",
        "Display products with multiple size availability.",
        "Find all-season boots for men.",
        "Are there color-changing shoes?",
        "Do you have shoes with memory foam?",
        "Show the best shoes for daily walking.",
        "Find sandals suitable for rainy season.",
        "Show limited edition sneakers.",
        "Do you have glow shoes for kids?",
        "List party wear footwear below ₹3000.",
        "I want gym shoes for ₹1000 to ₹2500.",
        "List exclusive premium shoes.",
        "Find ultra-lightweight footwear.",
        "Show breathable shoes for summers.",
        "Do you offer bulk order discounts?",
        "Show me designer shoes on offer.",
        "List festive collection footwear.",
        "Find cheapest shoes with good reviews.",
        "Display shoes with multi-color options."
    ]
)


index = LocalIndex()
router = SemanticRouter(
    encoder=encoder,
    routes=[faq, sql],
    index= index,
    auto_sync="local"
)

if __name__ == "__main__":
    print(router("What is your policy on defective products?").name)
    print(router("Pink Puma shoes in price range 5000 to 10000").name)
